/**
 * Timing Golden Vector Test (C++ side)
 *
 * Runs src/timing.h against shared/timing_golden.json — the same vectors
 * ui/js/tests/timeline_model_golden.test.mjs runs against timeline_model.js.
 * If both suites pass, the C++ and JS timing math agree. The continuity
 * re-anchor (heard_index.h) and the peak buckets (ClipNode::peakBucket)
 * pin their mock twins the same way (ui/js/tests/continuity_origin
 * .test.mjs, peak_density.test.mjs).
 */

#include <juce_core/juce_core.h>

#include <cmath>

#include "../src/clip_node.h"
#include "../src/heard_index.h"
#include "../src/sequence.h"
#include "../src/timing.h"
#include "test_utils.h"

using celestrian::test_utils::asInt64;
using celestrian::test_utils::findSharedFile;

class TimingGoldenTests : public juce::UnitTest {
 public:
  TimingGoldenTests() : juce::UnitTest("Timing Golden Vectors") {}

  void runTest() override {
    using celestrian::timing::armTarget;
    using celestrian::timing::launchPointFor;
    using celestrian::timing::lcm;
    using celestrian::timing::nextStopBoundary;
    using celestrian::timing::originQ;
    using celestrian::timing::QTime;
    using celestrian::timing::snapCommittedDuration;
    using celestrian::timing::throughMapDest;
    using celestrian::timing::TimeMap;
    using celestrian::timing::toSamples;

    beginTest("Load shared/timing_golden.json");
    auto file = findSharedFile("shared/timing_golden.json");
    expect(file.existsAsFile(),
           "shared/timing_golden.json not found (searched upward from cwd and "
           "executable dir)");
    if (!file.existsAsFile()) return;

    auto root = juce::JSON::parse(file.loadFileAsString());
    expect(root.isObject(), "golden file did not parse as JSON");
    if (!root.isObject()) return;

    beginTest("timeline LCM");
    if (auto* cases = root.getProperty("lcm_cases", {}).getArray()) {
      for (auto& c : *cases) {
        int64_t result = asInt64(c, "quantum");
        if (auto* durations = c.getProperty("durations", {}).getArray()) {
          for (auto& d : *durations) {
            int64_t dur = (int64_t)(double)d;
            if (dur > 0) result = lcm(result, dur);
          }
        }
        expectEquals((juce::int64)result, (juce::int64)asInt64(c, "expected"),
                     c.getProperty("name", "?").toString());
      }
    }

    beginTest("launchPointFor");
    if (auto* cases = root.getProperty("launch_point_cases", {}).getArray()) {
      for (auto& c : *cases) {
        expectEquals((juce::int64)launchPointFor(asInt64(c, "startPhase"),
                                                 asInt64(c, "duration")),
                     (juce::int64)asInt64(c, "expected"),
                     c.getProperty("name", "?").toString());
      }
    }

    // THE SEQUENCE PROGRAM (docs/sequencer.md §14): the successor walk
    // and its seeded draws must unroll identically in src/sequence.h
    // and ui/js/sequence_program.js — the vectors were generated by
    // the JS mirror.
    beginTest("sequence program (successor graphs + the seed)");
    if (auto* cases = root.getProperty("sequence_program_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const juce::String name = c.getProperty("name", "?").toString();
        celestrian::Sequence s;
        if (auto* steps = c.getProperty("steps", {}).getArray()) {
          for (auto& sv : *steps) {
            celestrian::Sequence::Step st;
            st.len = asInt64(sv, "len");
            celestrian::Sequence::readSuccessors(sv, st);
            s.steps.push_back(std::move(st));
          }
        }
        s.seed = (uint32_t)asInt64(c, "seed");
        s.finalize();
        expectEquals((int)s.radio, (int)(bool)c.getProperty("radio", false),
                     name + " - radio");
        expectEquals((juce::int64)s.total, (juce::int64)asInt64(c, "total"),
                     name + " - total");
        expectEquals(s.visit_count, (int)c.getProperty("visitCount", 0),
                     name + " - visit count");
        if (auto* visits = c.getProperty("visits", {}).getArray()) {
          for (int k = 0; k < visits->size() && k < s.visit_count; ++k) {
            expectEquals(s.visit_step[k], (int)(*visits)[k],
                         name + " - visit " + juce::String(k));
          }
        }
      }
    }

    beginTest("armTarget");
    if (auto* cases = root.getProperty("arm_target_cases", {}).getArray()) {
      for (auto& c : *cases) {
        expectEquals(
            (juce::int64)armTarget(asInt64(c, "rel"), asInt64(c, "quantum"),
                                   asInt64(c, "contextLoop")),
            (juce::int64)asInt64(c, "expected"),
            c.getProperty("name", "?").toString());
      }
    }

    beginTest("nextStopBoundary");
    if (auto* cases = root.getProperty("stop_boundary_cases", {}).getArray()) {
      for (auto& c : *cases) {
        expectEquals((juce::int64)nextStopBoundary(asInt64(c, "recordedLength"),
                                                   asInt64(c, "quantum")),
                     (juce::int64)asInt64(c, "expected"),
                     c.getProperty("name", "?").toString());
      }
    }

    beginTest("snapCommittedDuration");
    if (auto* cases = root.getProperty("snap_cases", {}).getArray()) {
      for (auto& c : *cases) {
        auto name = c.getProperty("name", "?").toString();
        auto result = snapCommittedDuration(asInt64(c, "recordedLength"),
                                            asInt64(c, "quantum"));
        expectEquals((juce::int64)result.duration,
                     (juce::int64)asInt64(c, "expectedDuration"),
                     name + " (duration)");
        expectEquals((juce::int64)result.loop_end,
                     (juce::int64)asInt64(c, "expectedLoopEnd"),
                     name + " (loop_end)");
        expect(result.snapped == (bool)c.getProperty("expectedSnapped", false),
               name + " (snapped)");
      }
    }

    // Shared helper: build a TimeMap from a golden case's "segments".
    auto mapFrom = [this](const juce::var& c, const juce::String& name,
                          const char* key = "segments") {
      TimeMap m;
      if (auto* segs = c.getProperty(key, {}).getArray()) {
        for (auto& s : *segs) {
          auto* pair = s.getArray();
          expect(pair != nullptr && pair->size() == 2 &&
                     m.n < TimeMap::kMaxSegments,
                 name + " (segment shape)");
          if (pair == nullptr || pair->size() != 2) continue;
          m.segs[m.n++] = {(int64_t)(double)(*pair)[0],
                           (int64_t)(double)(*pair)[1]};
        }
      }
      return m;
    };

    beginTest("through-map arm (heard armTarget on the map-period grid)");
    if (auto* cases =
            root.getProperty("through_map_arm_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const auto name = c.getProperty("name", "?").toString();
        const TimeMap m = mapFrom(c, name);
        const int64_t t_rel = armTarget(asInt64(c, "relHeard"),
                                        asInt64(c, "quantum"), m.period());
        expectEquals((juce::int64)t_rel,
                     (juce::int64)asInt64(c, "expectedHeardTargetRel"),
                     name + " (heard target)");
        expectEquals((juce::int64)m.mapOffset(t_rel),
                     (juce::int64)asInt64(c, "expectedInnerOffset"),
                     name + " (inner offset)");
      }
    }

    beginTest("through-map capture fold (throughMapDest)");
    if (auto* cases =
            root.getProperty("through_map_dest_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const auto name = c.getProperty("name", "?").toString();
        const TimeMap m = mapFrom(c, name);
        if (auto* probes = c.getProperty("probes", {}).getArray()) {
          for (auto& p : *probes) {
            expectEquals(
                (juce::int64)throughMapDest(asInt64(p, "i"),
                                            asInt64(c, "anchorOff"), m,
                                            asInt64(c, "commitCycle")),
                (juce::int64)asInt64(p, "dest"),
                name + " dest(i=" + juce::String(asInt64(p, "i")) + ")");
          }
        }
      }
    }

    beginTest("TimeMap inverse (heardOffsetOf)");
    if (auto* cases = root.getProperty("map_inverse_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const auto name = c.getProperty("name", "?").toString();
        const TimeMap m = mapFrom(c, name);
        if (auto* probes = c.getProperty("probes", {}).getArray()) {
          for (auto& p : *probes) {
            expectEquals((juce::int64)m.heardOffsetOf(asInt64(p, "inner")),
                         (juce::int64)asInt64(p, "heard"),
                         name + " heardOffsetOf(" +
                             juce::String(asInt64(p, "inner")) + ")");
          }
        }
      }
    }

    beginTest("TimeMap (reified map: period / mapOffset / seamDistance)");
    if (auto* cases = root.getProperty("time_map_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const auto name = c.getProperty("name", "?").toString();
        const TimeMap m = mapFrom(c, name);
        expectEquals((juce::int64)m.period(),
                     (juce::int64)asInt64(c, "expectedPeriod"),
                     name + " (period)");
        if (auto* probes = c.getProperty("probes", {}).getArray()) {
          for (auto& p : *probes) {
            const auto h = juce::String(asInt64(p, "h"));
            expectEquals((juce::int64)m.mapOffset(asInt64(p, "h")),
                         (juce::int64)asInt64(p, "inner"),
                         name + " mapOffset(h=" + h + ")");
            expectEquals((juce::int64)m.seamDistance(asInt64(p, "h")),
                         (juce::int64)asInt64(p, "seam"),
                         name + " seamDistance(h=" + h + ")");
          }
        }
      }
    }

    beginTest("innerAt (THE RENDER EQUATION, stated once)");
    if (auto* cases = root.getProperty("inner_at_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const auto name = c.getProperty("name", "?").toString();
        const TimeMap m = mapFrom(c, name);
        const int64_t origin = asInt64(c, "origin");
        const int64_t fold = asInt64(c, "fold");
        if (auto* probes = c.getProperty("probes", {}).getArray()) {
          for (auto& p : *probes) {
            const auto t = juce::String(asInt64(p, "t"));
            const celestrian::timing::InnerAt at =
                celestrian::timing::innerAt(asInt64(p, "t"), origin, m, fold);
            expectEquals((juce::int64)at.h, (juce::int64)asInt64(p, "h"),
                         name + " h(t=" + t + ")");
            expectEquals((juce::int64)at.inner,
                         (juce::int64)asInt64(p, "inner"),
                         name + " inner(t=" + t + ")");
            expectEquals((juce::int64)at.run, (juce::int64)asInt64(p, "run"),
                         name + " run(t=" + t + ")");
            expect(at.rest == (bool)p.getProperty("rest", false),
                   name + " rest(t=" + t + ")");
          }
        }
      }
    }
    {
      // forEachContentRun: the comp cell length is a seam input — a run
      // never crosses a Q cell of the inner position, a map seam, or
      // the shot end; the runs tile the block exactly.
      TimeMap m;
      m.n = 2;
      m.segs[0] = {0, 300};
      m.segs[1] = {600, 1000};  // shot 700
      std::vector<std::pair<int, int>> runs;  // (i, run)
      std::vector<int64_t> inners;
      celestrian::timing::forEachContentRun(
          0, 1000, 0, m, /*fold=*/700, /*cell_len=*/250,
          [&](int i, int run, const celestrian::timing::InnerAt& at) {
            runs.push_back({i, run});
            inners.push_back(at.inner);
          });
      // h: 0 → cell edge 250; 250 → seam at 300 (50); 300 → inner 600,
      // cell edge 750 (150); 450 → inner 750, seam/cell 1000 (250);
      // 700 = a new pass, h 0 (250); 950 → 50 left in the block.
      const std::vector<std::pair<int, int>> want = {
          {0, 250}, {250, 50}, {300, 150}, {450, 250}, {700, 250}, {950, 50}};
      expect(runs == want, "runs tile the block at cells, seams and passes");
      const std::vector<int64_t> want_inner = {0, 250, 600, 750, 0, 250};
      expect(inners == want_inner, "each run starts at its inner position");
      int covered = 0;
      for (const auto& r : runs) covered += r.second;
      expectEquals(covered, 1000, "the runs cover the block exactly");
    }

    beginTest("the continuity re-anchor (nearest representative, SM-4)");
    if (auto* cases =
            root.getProperty("nearest_representative_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const int64_t x = asInt64(c, "x"), ref = asInt64(c, "ref"),
                      m = asInt64(c, "m");
        expectEquals((juce::int64)celestrian::heard::nearestRepresentative(x, ref, m),
                     (juce::int64)asInt64(c, "expected"),
                     "nearestRepresentative(" + juce::String(x) + ", " +
                         juce::String(ref) + ", " + juce::String(m) + ")");
      }
    }
    if (auto* cases = root.getProperty("continuity_origin_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const auto name = c.getProperty("name", "?").toString();
        const TimeMap oldm = mapFrom(c, name, "oldSegments");
        const TimeMap newm = mapFrom(c, name, "newSegments");
        const int64_t got = celestrian::heard::continuityOriginFor(
            oldm, newm, asInt64(c, "origin"), asInt64(c, "t0"),
            asInt64(c, "oldFold"), asInt64(c, "newFold"));
        expectEquals((juce::int64)got, (juce::int64)asInt64(c, "expected"), name);
        // And the answer keeps the sounding sample sounding (or, when
        // the origin stayed, the case says why).
        const auto before = celestrian::timing::innerAt(
            asInt64(c, "t0"), asInt64(c, "origin"), oldm, asInt64(c, "oldFold"));
        const auto after = celestrian::timing::innerAt(
            asInt64(c, "t0"), got, newm, asInt64(c, "newFold"));
        if (!before.rest && newm.heardOffsetOf(before.inner) >= 0) {
          expectEquals((juce::int64)after.inner, (juce::int64)before.inner,
                       name + " (the sounding sample keeps sounding)");
        }
      }
    }

    beginTest("peak buckets (proportional bounds, N7)");
    if (auto* cases = root.getProperty("peak_bucket_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const int64_t total = asInt64(c, "total");
        const int n = (int)asInt64(c, "n");
        if (auto* buckets = c.getProperty("buckets", {}).getArray()) {
          for (auto& b : *buckets) {
            const int i = (int)(double)b[0];
            const auto got = celestrian::ClipNode::peakBucket(i, total, n);
            const juce::String name = "bucket " + juce::String(i) + " of " +
                                      juce::String(n) + " over " +
                                      juce::String(total);
            expectEquals((juce::int64)got.start, (juce::int64)(double)b[1],
                         name + " start");
            expectEquals((juce::int64)got.end, (juce::int64)(double)b[2],
                         name + " end");
          }
        }
      }
    }

    beginTest("originQ (D-T3 physical/musical boundary projection)");
    if (auto* cases = root.getProperty("qtime_origin_cases", {}).getArray()) {
      for (auto& c : *cases) {
        const auto name = c.getProperty("name", "?").toString();
        const QTime q = originQ(asInt64(c, "origin"), asInt64(c, "zero"),
                                asInt64(c, "qSamples"));
        expectEquals((juce::int64)q.num, (juce::int64)asInt64(c, "expectedNum"),
                     "originQ num: " + name);
        expectEquals((juce::int64)q.den, (juce::int64)asInt64(c, "expectedDen"),
                     "originQ den: " + name);
        // The boundary must be lossless at the same exchange rate:
        // projecting to Q and back lands on the exact sample offset (I1).
        expectEquals((juce::int64)toSamples(q, asInt64(c, "qSamples")),
                     (juce::int64)(asInt64(c, "origin") - asInt64(c, "zero")),
                     "originQ round-trip: " + name);
      }
    }
  }
};

static TimingGoldenTests timingGoldenTests;
